# Optional setting, 8080 by default
server:
  port: 8080 

spring:
  application:
    name: spring-datarest-demo
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:mem:testdb
    driver-className: org.h2.Driver
    username: sa
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    hibernate:
      ddl-auto: create

# Displays all actuator endpoints
management:
  endpoints:
    web:
      exposure:
        include: "*"