#server:
#  port: 8080
  
spring:
  application.name: gateway
  cloud:
    gateway:
      default-filters:
      - PrefixPath=/
      routes:
      - id: flashcard
#lb tells Spring Cloud Gateway to load balance across all of the instances of the services with that name
        uri: lb://flashcard
        predicates:
        - Path=/flashcard/**
        filters:
        - StripPrefix=1
      - id: quiz
        uri: lb://quiz
        predicates:
        - Path=/quiz/**
        filters:
        - StripPrefix=1
      
